name: Run Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run E2E tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run serve

      - name: Run unit tests 
        run: npm run test:unit